### ISSUE TITLE
Emojis & Reactions appearing over-sized.

### ISSUE THREAD

**Issue by Questica** [ObserverOfTime/DiscordThemes#2]
## Emojis should be a similar size to text, and reactions should be the same size.

Emojis are over-sized, as well as reactions. https://i.imgur.com/Oo1U2cS.png

Love this theme been using it for awhile, used to use custom css to make emojis larger and reactions never had a problem. I recently updated to the new repo of the theme and now reactions have the same problem and I couldn't find a custom css solution. I tried to look through all my other plugins and settings to figure out what was causing it but couldn't find a culprit.

I run into some other problems with lag loading server member lists and server invites that don't happen with the theme off or even in the web version of discord, but those aren't that big of a deal, this emoji thing is making me go crazy.

**Comment by ObserverOfTime** [comment]
> Emojis are over-sized, as well as reactions.

The emoji size is controlled by this section:
https://github.com/ObserverOfTime/DiscordThemes/blob/0536ac22461a068f07329a6d9f8e908d52839635/NewNihilism/dist/NewNihilism.theme.css#L234-L243
There aren't any configuration variables but you can reset it with the following custom CSS:
```css
#app-mount .emoji {
    width: 1.45em;
    height: 1.45em;
    max-width: unset !important;
}

#app-mount .emoji.jumboable {
    height: 2rem;
    width: 2rem;
}
```

> I run into some other problems with lag loading server member lists and server invites

Personally, I haven't noticed any lagging. Are you certain it's caused by my theme?
