### ISSUE TITLE
Avatars do not fit in the box with NewNihilism

### ISSUE THREAD

**Issue by Fuyucch1** [ObserverOfTime/DiscordThemes#4]
On the Activity Page, avatars do not fit in the box they are meant to:
![example](https://i.imgur.com/UGd3r0F.png)

This is what I wrote so it fixes it, but it isn't as good as what you guys can do :
```css
.da-outer .image-33JSyf {
  width: 30px !important;
    height: 30px !important
}

.memberListContainer-1AKCDy .image-33JSyf {
  width: 20px !important;
    height: 20px !important
}
```
![example](https://i.imgur.com/9NGbV3P.png)
