### ISSUE TITLE
Help can't see it how to change color

### ISSUE THREAD

**Issue by dMoonShadowElf** [ObserverOfTime/DiscordThemes#5]
my friend is colorblind and has trouble seeing number counter on the number badge 
notifcation counter 

is there away  to change the color of it to something easier for them to see

**Comment by ObserverOfTime** [comment]
Oh, whoops, I forgot about this issue.
Add this to the custom CSS and adjust the colors however you like.
```css
.numberBadge-2s8kKX {
    background-color: white !important;
    color: black;
}
```
